version: 2.1
orbs:
  python: circleci/python@2.1.1
  aws-cli: circleci/aws-cli@4.1.2
jobs:
  build-and-test:
    executor:
      name: python/default
      tag: '3.10'
    steps:
      - checkout
      - run:
          name: Setup Virtual Env
          command: |
            virtualenv -p 3.10 venv
            echo "source ./venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Test
          command: pytest
      - run:
          name: Zip Dependencies
          command: |
            cd venv/lib/python3.10/site-packages
            zip -r9 ../../../../packer.zip .
      - run:
          name: Zip the App
          command: zip -g ./packer.zip -r app
      - persist_to_workspace:
          root: .
          paths:
            - packer.zip
  deploy-dev:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ./
      - aws-cli/configure:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_KEY_ID
      - run:
          name: Upload to S3
          command: aws s3 cp packer.zip s3://packer-lambda/packer.zip
      - run:
          name: Deploy Lambda
          command: aws lambda update-function-code --function-name packer-lambda --s3-bucket packer-deploy --s3-key packer.zip

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test:
          context: CircleCI-packer-deploy
          filters:
            branches:
              only:
                - master
      - deploy-dev:
          context: CircleCI-packer-deploy
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master