version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-test:
    executor:
      name: python/default
      tag: '3.10'
    steps:
      - checkout
      - run:
          name: Setup Virtual Env
          command: |
            virtualenv -p 3.10 venv
            echo "source ./venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Test
          command: pytest
      - run:
          name: Zip Dependencies
          command: |
            cd venv/lib/python3.10/site-packages
            zip -r9 ../../../../packer.zip .
      - run:
          name: Zip the App
          command: zip -g ./function.zip -r packer

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master